import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { decodeCodePage, CODE_PAGES, describeCodePage } from '../services/ipl/codePages';
import { parseViewerIPL } from '../services/ipl/viewerParser';
import type { TextElement } from '../services/ipl/types';

const stx = (f: string) => `<STX>${f}<ETX>`;

/** One char per byte, the shape the whole pipeline carries. */
const bytes = (...v: number[]) => String.fromCharCode(...v);

const textEl = (label: ReturnType<typeof parseViewerIPL>, i = 0) =>
    label.elements.filter(e => e.kind === 'text')[i] as TextElement;

describe('code page tables match the iconv goldens', () => {
    // Every byte of every table is pinned to GNU iconv output. The golden files
    // are the audit trail: they are generated by tools/gen-codepages.mjs and
    // read here so the test needs no iconv on the machine running it.
    for (const n of [10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]) {
        it(`n=${n} (${CODE_PAGES[n].label}) decodes all 128 high bytes`, () => {
            const golden = JSON.parse(
                readFileSync(join(__dirname, '..', 'testdata', 'codepages', `${n}.json`), 'utf8'),
            ) as { n: number; iconv: string; table: number[] };
            expect(golden.n).toBe(n);
            for (let b = 0x80; b <= 0xff; b++) {
                const got = decodeCodePage(bytes(b), n);
                const want = String.fromCodePoint(golden.table[b - 0x80]);
                expect(`${b.toString(16)}=${got}`).toBe(`${b.toString(16)}=${want}`);
            }
        });
    }
});

describe('decodeCodePage', () => {
    it('leaves ASCII untouched in every page', () => {
        for (const n of [10, 11, 12, 13, 20, 40]) {
            expect(decodeCodePage('ABC-123', n)).toBe('ABC-123');
        }
    });

    it('tells cp1252 and cp850 apart on the same byte', () => {
        // 0x84 is the discriminating case: "ä" in cp850, a low quote in cp1252.
        // If this passes, decoding is genuinely table-driven and not a Latin-1
        // accident that happens to look right for 0xE4.
        expect(decodeCodePage(bytes(0x84), 10)).toBe('ä');
        expect(decodeCodePage(bytes(0x84), 13)).toBe('„');
    });

    it('decodes cp850 German characters', () => {
        expect(decodeCodePage(bytes(0x84, 0x94, 0x81), 10)).toBe('äöü');
    });

    it('decodes cp1252 Western European characters', () => {
        expect(decodeCodePage(bytes(0xe4, 0xf6, 0xfc, 0xdf), 13)).toBe('äöüß');
    });

    it('decodes cp1251 Cyrillic', () => {
        expect(decodeCodePage(bytes(0xc0, 0xc1, 0xc2), 12)).toBe('АБВ');
    });

    it('decodes cp1250 Central European', () => {
        // 0xB1 is plus-minus in cp1250; the a-ogonek is 0xB9.
        expect(decodeCodePage(bytes(0xb1, 0xb9, 0xe1), 11)).toBe('±ąá');
    });

    it('maps unassigned bytes to U+FFFD instead of throwing', () => {
        // cp1252 leaves 0x81/0x8D/0x8F/0x90/0x9D undefined.
        expect(decodeCodePage(bytes(0x81), 13)).toBe('�');
    });

    it('decodes UTF-8 (n=40) from raw bytes', () => {
        expect(decodeCodePage(bytes(0xc3, 0xa4), 40)).toBe('ä');
    });

    it('does not guess for resident languages (n=0..9)', () => {
        // These are Appendix B character SUBSTITUTIONS, not code pages; the
        // bytes must reach the renderer untouched.
        for (const n of [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) {
            expect(decodeCodePage(bytes(0x84, 0x94), n)).toBe(bytes(0x84, 0x94));
        }
    });

    it('does not guess for CJK pages (n=30..33)', () => {
        for (const n of [30, 31, 32, 33]) {
            expect(decodeCodePage(bytes(0x84), n)).toBe(bytes(0x84));
        }
    });

    it('returns the input for an unknown page', () => {
        expect(decodeCodePage(bytes(0x84), 99)).toBe(bytes(0x84));
    });

    it('returns the input when no page is selected', () => {
        expect(decodeCodePage(bytes(0x84), undefined)).toBe(bytes(0x84));
    });

    it('decodes each byte exactly once from a byte-string', () => {
        // Idempotence is NOT universal and cannot be: cp850/cp1255/cp1257 map
        // several bytes onto code points that are themselves in U+0080-U+00FF
        // (0x81 -> ü in cp850), so a decoded string is indistinguishable from a
        // raw byte-string. Decoding is applied once per item at exactly two
        // call sites, never twice over the same text.
        expect(decodeCodePage(bytes(0x84, 0xe4, 0x41), 13)).toBe('„äA');
    });

    it('leaves already-Unicode text alone instead of folding it into a byte', () => {
        // U+20AC & 0xff is 0xAC, which cp850 maps to a quarter sign — a user who
        // types "Preis 5€" under <SI>l10 must not watch it become "Preis 5¼".
        // Only chars ABOVE U+00FF are unambiguously real text; below that they
        // are indistinguishable from bytes, and the byte reading is the correct
        // one for a stream.
        expect(decodeCodePage('Preis 5€', 10)).toBe('Preis 5€');
        expect(decodeCodePage('x„y', 13)).toBe('x„y');
    });

    it('passes high-plane Unicode through the UTF-8 page', () => {
        // Only chars above U+00FF are unambiguously text; U+00EF (ï) is
        // indistinguishable from byte 0xEF, which UTF-8 would read as the
        // start of a multi-byte sequence. The byte reading is correct for a
        // stream, so this pins that boundary deliberately.
        expect(decodeCodePage('naïve 5€', 40)).toBe('na�ve 5€');
        expect(decodeCodePage('emoji 😀 here', 40)).toBe('emoji 😀 here');
    });
});

describe('<SI>l parsing', () => {
    it('records the selected code page on the label', () => {
        const label = parseViewerIPL(
            [stx('<ESC>P'), stx('<SI>l13'), stx('E1;F1'), stx('H0;o10,10;c0;d3,0,HI'), stx('R'), stx('<ESC>E1')].join(''),
        );
        expect(label.settings.codePage).toBe(13);
    });

    it('decodes fixed d3 data under the selected page', () => {
        const label = parseViewerIPL(
            [stx('<ESC>P'), stx('<SI>l10'), stx('E1;F1'),
             stx('H0;o10,10;c25;k12;d3,' + bytes(0x84, 0x94)), stx('R'), stx('<ESC>E1')].join(''),
        );
        expect(textEl(label).source).toEqual({ type: 'fixed', data: 'äö' });
    });

    it('decodes print-block variable data under the selected page', () => {
        const label = parseViewerIPL(
            [stx('<ESC>P'), stx('<SI>l10'), stx('E1;F1'), stx('H0;o10,10;c25;k12;d1'), stx('R'),
             stx('<ESC>E1<CAN><ESC>F0<NUL>' + bytes(0x84, 0x94, 0x81) + '<ETB><FF>')].join(''),
        );
        expect(textEl(label).source).toEqual({ type: 'variable', data: 'äöü' });
    });

    it('is a no-op when the stream selects no code page', () => {
        const frames = [stx('E1;F1'),
                        stx('H0;o10,10;c25;k12;d3,' + bytes(0x84, 0x94)), stx('R'), stx('<ESC>E1')];
        const without = parseViewerIPL([stx('<ESC>P'), ...frames].join(''));
        const withDefault = parseViewerIPL([stx('<ESC>P'), stx('<SI>l0'), ...frames].join(''));
        expect(withDefault.settings.codePage).toBe(0);
        expect(textEl(withDefault).source).toEqual(textEl(without).source);
    });

    it('warns for a CJK page and still renders', () => {
        const label = parseViewerIPL(
            [stx('<ESC>P'), stx('<SI>l30'), stx('E1;F1'), stx('H0;o10,10;c25;k12;d3,ABC'), stx('R'), stx('<ESC>E1')].join(''),
        );
        expect(label.issues.some(i => i.code === 'code-page-cjk')).toBe(true);
        expect(textEl(label).source).toEqual({ type: 'fixed', data: 'ABC' });
    });

    it('warns for an undocumented page number', () => {
        const label = parseViewerIPL(
            [stx('<ESC>P'), stx('<SI>l77'), stx('E1;F1'), stx('H0;o10,10;c25;k12;d3,ABC'), stx('R'), stx('<ESC>E1')].join(''),
        );
        expect(label.issues.some(i => i.code === 'code-page-unknown')).toBe(true);
    });

    it('warns when a code page meets a resident bitmap font', () => {
        // PRM p.134: code pages 11..33 do not work with resident fonts.
        const label = parseViewerIPL(
            [stx('<ESC>P'), stx('<SI>l13'), stx('E1;F1'), stx('H0;o10,10;c0;d3,ABC'), stx('R'), stx('<ESC>E1')].join(''),
        );
        expect(label.issues.some(i => i.code === 'code-page-resident-font')).toBe(true);
    });

    it('does not warn for an outline font, which can use a code page', () => {
        const label = parseViewerIPL(
            [stx('<ESC>P'), stx('<SI>l13'), stx('E1;F1'), stx('H0;o10,10;c25;k12;d3,ABC'), stx('R'), stx('<ESC>E1')].join(''),
        );
        expect(label.issues.some(i => i.code === 'code-page-resident-font')).toBe(false);
    });

    it('does not apply the resident-font warning to UTF-8 (n=40)', () => {
        // PRM p.134 scopes the limitation to code pages 11..33; n=40 (2.70) is
        // outside it and a false warning here would train users to ignore it.
        const label = parseViewerIPL(
            [stx('<ESC>P'), stx('<SI>l40'), stx('E1;F1'), stx('H0;o10,10;c0;d3,ABC'), stx('R'), stx('<ESC>E1')].join(''),
        );
        expect(label.issues.some(i => i.code === 'code-page-resident-font')).toBe(false);
    });

    it('decodes each print block with the page in effect when it was sent', () => {
        // A job that switches language between labels must not render the first
        // label with the second label's characters. This goes through
        // parseViewerIPL so the parser's own timeline is exercised, not a
        // hand-made callback.
        const frames = (lang: string) => [stx('<ESC>P'), stx('E1;F1'), stx('H0;o10,10;c25;k12;d1'), stx('R'),
                      stx(lang),
                      stx('<ESC>E1<CAN><ESC>F0<NUL>' + bytes(0xe4, 0xe0) + '<ETB><FF>')].join('');

        // cp1252: 0xE4/0xE0 are ä and à.
        expect(textEl(parseViewerIPL(frames('<SI>l13'))).source)
            .toEqual({ type: 'variable', data: 'äà' });
        // cp1251: the same two bytes are Cyrillic д and а.
        expect(textEl(parseViewerIPL(frames('<SI>l12'))).source)
            .toEqual({ type: 'variable', data: 'да' });
    });

    it('keeps a later code page from retroactively changing an earlier block', () => {
        // The block precedes the switch, so it stays cp1252 even though the
        // stream's final settings report cp1251.
        const code = [stx('<ESC>P'), stx('E1;F1'), stx('H0;o10,10;c25;k12;d1'), stx('R'),
                      stx('<SI>l13'),
                      stx('<ESC>E1<CAN><ESC>F0<NUL>' + bytes(0xe4, 0xe0) + '<ETB><FF>'),
                      stx('<SI>l12')].join('');
        const label = parseViewerIPL(code);
        expect(label.settings.codePage).toBe(12);
        expect(textEl(label).source).toEqual({ type: 'variable', data: 'äà' });
    });
});

describe('describeCodePage', () => {
    it('names a decodable page', () => {
        expect(describeCodePage(13)).toContain('CP1252');
    });
    it('flags resident substitution separately from decoding', () => {
        expect(describeCodePage(2)).toContain('resident');
    });
    it('says when a page is not decoded', () => {
        expect(describeCodePage(31)).toContain('not decoded');
    });
});
