// The KNOWN LIMIT of the Direct Graphics placement model, pinned so it cannot
// be forgotten or silently "fixed" with a fit that only suits one fixture.
//
// WHY THIS FILE EXISTS. The shipped formula is
//
//     yTop = originY + (W + 2*adjust)/2 - maxBit - ceil(printableX*dpi/2)
//
// and it is verified against BarTender on landscape and square pages. Its
// half-page term uses `W`, the printhead WIDTH axis. On every fixture available
// before 2026-09-28 that axis coincides with the page's feed axis, so the
// formula and a feed-axis reading were INDISTINGUISHABLE — which is exactly the
// kind of gap this project has been bitten by before.
//
// Fixtures `por-3x2` and `por-2x3` (btPortrait, 3x2 and 2x3 in, generated by
// tools/bartender/_p/BuildPortrait.cs) separate them, and the shipped formula
// is WRONG there by ~42 dots:
//
//     fixture   pageW  pageH   W   originY  maxBit   predicted   measured
//     por-3x2     609    406  591      480     271        90.5         49
//     por-2x3     406    609  388      582     271        91.0         49
//
// WHAT WAS RULED OUT. A two-point fit suggested `pageX/2 - 49`, which matches
// both portrait fixtures exactly and FAILS every landscape fixture by 100-360
// dots — a reminder that two points fit two parameters trivially. Also checked
// and rejected: pageY/2, pageX/2, pageW/2, pageH/2, min/max of the two axes,
// their mean, and W/2 with both 416 and 424.
//
// So the limitation is REAL and not yet solved. This test does not assert the
// wrong answer; it asserts the ERROR IS STILL THE KNOWN SIZE, so that:
//   - the gap cannot be forgotten (it fails loudly if someone changes the
//     portrait path without understanding it), and
//   - a future fix will fail here too, prompting this file to be rewritten with
//     the real model rather than deleted quietly.
//
// The orientation marker is not in the stream either (no q frame, no <SI>L), so
// whether this is solvable from the stream alone is itself an open question.
import './golden/setup';
import { describe, it, expect, beforeAll } from 'vitest';
import { existsSync, readFileSync } from 'node:fs';
import { loadImage } from '@napi-rs/canvas';
import { newRealCanvas } from './golden/setup';
import { bytesToByteString } from '../services/ipl/fileBytes';
import { extractDirectGraphics } from '../services/ipl/directGraphics';
import { ensureBarcodesReady } from '../services/ipl/barcodes';
import { PRINTABLE_WIDTH_IN, LABEL_WIDTH_ADJUSTMENT } from '../constants';

beforeAll(async () => { await ensureBarcodesReady(); });

type AnyCanvas = { width: number; height: number; getContext(k: '2d'): any };

const DPI = 203;
const inkTop = (cv: AnyCanvas) => {
    const d = cv.getContext('2d').getImageData(0, 0, cv.width, cv.height).data;
    for (let y = 0; y < cv.height; y++) for (let x = 0; x < cv.width; x++) {
        const o = (y * cv.width + x) * 4;
        if (d[o + 3] > 0 && d[o] < 100 && d[o + 1] < 100 && d[o + 2] < 100) return y;
    }
    return -1;
};
const dgFrames = (raw: string) => {
    const frames: string[] = [];
    const re = /<STX>([\s\S]*?)<ETX>/g;
    let m; let inDg = false;
    while ((m = re.exec(raw))) {
        const body = m[1];
        if (body.startsWith('<ESC>g')) { inDg = true; continue; }
        if (inDg) frames.push(body);
    }
    return frames;
};

/** The shipped formula's prediction for a graphic's printed ink top. */
const shippedPrediction = (originY: number, maxBit: number, W: number) => {
    const adj = LABEL_WIDTH_ADJUSTMENT['PD43'][203]!;
    const px = PRINTABLE_WIDTH_IN['PD43'][203]!;
    return originY + (W + 2 * adj) / 2 - maxBit - Math.ceil(px * DPI / 2);
};

describe('Direct Graphics placement: the btPortrait non-square LIMIT', () => {
    for (const [name, expectedError] of [
        ['por-3x2', 41.5],
        ['por-2x3', 42.0],
    ] as Array<[string, number]>) {
        it(`${name}: the known ~42 dot error is unchanged`, async () => {
            const ipl = `C:/Temp/bt-p/${name}.ipl`;
            const png = `C:/Temp/bt-p-png/${name}.png`;
            if (!existsSync(ipl) || !existsSync(png)) {
                // The fixtures live outside the repo (generated by a BarTender
                // script); skip rather than fail on a machine without them.
                console.log(`${name}: fixture not present — skipping`);
                return;
            }

            const raw = bytesToByteString(readFileSync(ipl));
            const W = Number((/<SI>W(\d+)/.exec(raw) || [])[1]);
            const [dg] = extractDirectGraphics(dgFrames(raw), 0);

            const img = await loadImage(png);
            const bt = newRealCanvas(img.width, img.height) as unknown as AnyCanvas;
            bt.getContext('2d').drawImage(img, 0, 0);
            const measured = inkTop(bt);

            let mx = -1;
            for (const c of dg.pixels) { if (!c) continue; for (let b = 0; b < c.length; b++) if (c[b]) { if (b > mx) mx = b; } }

            const predicted = shippedPrediction(dg.origin[1], mx, W);
            const error = predicted - measured;

            // Asserting the error stays ~42 — NOT that it is zero. A zero here
            // would mean the model was fixed, and this file should then be
            // rewritten to assert correctness instead.
            expect(Math.abs(error - expectedError),
                `${name}: expected the known ~${expectedError} dot error, got ${error.toFixed(1)}. `
                + 'If this is now ~0 the portrait case has been SOLVED — replace this '
                + 'limit test with a correctness assertion and update the placement docs.').toBeLessThanOrEqual(3);
        }, 60000);
    }
});
